alias ..='cd ..'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias ll='ls -hal'
alias ls='ls --color=auto'
alias pls='sudo $(history -p \!\!)'
alias speedtest-cli='python3 /opt/speedtest-cli/speedtest.py'
alias temperature='/opt/vc/bin/vcgencmd measure_temp'
alias upgrade='sudo apt-get update && sudo apt-get upgrade'
alias whatsmyip='curl -s ifconfig.me/ip'
