alias ..='cd ..'
alias pls='sudo $(history -p \!\!)'
alias speedtest-cli='python3 /opt/speedtest-cli/speedtest.py'
alias temperature='/opt/vc/bin/vcgencmd measure_temp'
alias upgrade='sudo apt update && sudo apt upgrade'
alias whatsmyip='curl -s ifconfig.me/ip'
